### ISSUE TITLE
Is it compatible with earlier ros ( ros 1 )

### ISSUE THREAD

**Issue by sumitsarkar1** [OpenVSLAM-Community/openvslam_ros#14]
I noticed there are two branches here for ros2 and ros. However when I clone ros in my catkin_ws/src and do catkin_make in catkin_ws/ it says openvslam_ros is not a catkin package ..its simply cmake package. `openvslam_ros (plain cmake)`

**Comment by ymd-stella** [comment]
ros branch has been confirmed to work with ROS noetic.

https://github.com/OpenVSLAM-Community/openvslam_ros/blob/7d9bd824f1eb588e65a4dad513780111b55cebe5/wercker.yml#L59

I have no idea why it is treated as plain cmake, so if you know, please let me know.

**Comment by ymd-stella** [comment]
I'm closing this as it doesn't seem to provide any additional information. If you can help, please feel free to reopen it.
