### ISSUE TITLE
Use a future timestamp

### ISSUE THREAD

**Issue by ymd-stella** [OpenVSLAM-Community/openvslam_ros#21]
Related to https://github.com/OpenVSLAM-Community/openvslam_ros/pull/9#discussion_r600348789.

**Comment by fadlio** [comment]
I'm getting `Transform failed: Lookup would require extrapolation into the future.` when using robot_localization to publish my `odom`=>`base_link` transform, could this be related to this issue?

**Comment by mirellameelo** [comment]
@fadlio I believe so. Could you update your comment with the rest of the error? I think is something like "Requested time X, but the latest... ".  
Please, try adding a tolerance time [here](https://github.com/OpenVSLAM-Community/openvslam_ros/blob/ac734513967893a584e2cff1b3fba450be782bc5/src/openvslam_ros.cc#L69) (`tf2::durationFromSec(your_timeout)`)

**Comment by fadlio** [comment]
@mirellameelo adding the timeout did the trick! Thank you!

**Comment by mirellameelo** [comment]
Nice! You're welcome. :)

@ymd-stella, I thought of adding this "transform_timeout" inside [setParam()](https://github.com/OpenVSLAM-Community/openvslam_ros/blob/ac734513967893a584e2cff1b3fba450be782bc5/src/openvslam_ros.cc#L86), how does it sound?
