### ISSUE TITLE
map_to_camera translation won't work well

### ISSUE THREAD

**Issue by AlexeyMerzlyakov** [OpenVSLAM-Community/openvslam_ros#26]
When running OpenVSLAM-ROS node with Gazebo, it was detected that robot's system coordinate (OXY plane for robot_frame-odom) is orthogonal to map system coordinate (OXY plane for map) as depicted below:
![issue_01_r](https://user-images.githubusercontent.com/60094858/122222650-203ce500-cebb-11eb-97aa-35016a848664.png)

For the camera frame z-axis is always looks in the same direction as the camera while map plane is rotated to have OXY plane to be parallel to map. So, the following translation is being applied:
![P10616-160721_r](https://user-images.githubusercontent.com/60094858/122225042-5ed39f00-cebd-11eb-9288-d0a9030dbb34.jpg)

It looks like the following place in the `openvslam_ros.cc` is responsible for that:
```
    Eigen::Matrix3d cv_to_ros;
    cv_to_ros << 0, 0, 1,
        -1, 0, 0,
        0, -1, 0;

    // Transform from CV coordinate system to ROS coordinate system on camera coordinates
    map_to_camera_affine.prerotate(cv_to_ros).rotate(cv_to_ros.transpose());
```

However, it is strange why the transform is being applied twice there? If we are applying some rotation, I think it will be enough just to multiply by rotation matrix once, e.g. as made [here](https://github.com/OpenVSLAM-Community/openvslam_ros/blob/ros2/src/openvslam_ros.cc#L29). Also, experiments shown that after the above part of code `map_to_camera_affine`  hasn't changed (related TF will be identical) if apply `prerotate(cv_to_ros).rotate(cv_to_ros.transpose())` to it.

So, I suppose that here should be something like this instead:
```
-    map_to_camera_affine.prerotate(cv_to_ros).rotate(cv_to_ros.transpose());
+    map_to_camera_affine.rotate(cv_to_ros);
```
or:
```
    Eigen::Matrix3d cv_to_ros;
    cv_to_ros << 0, 0, 1,
        -1, 0, 0,
        0, -1, 0;
    Eigen::Affine3d map_to_camera_affine(trans * rot * cv_to_ros);
```
without further `rotate()` routine.

Both cases are works well for me: map and camera's planes became to be correctly aligned.
Any thoughts on that?

**Comment by ymd-stella** [comment]
How is the tf between base_link and camera_link given?

**Comment by ymd-stella** [comment]
~~I don't think cv_to_ros is necessary at all. I originally used it to convert to the ROS coordinate system when camera_link didn't exist, and mistakenly ignored it. When you have confirmed that it works without cv_to_ros, I will remove cv_to_ros.~~

I originally used cv_to_ros to convert to the ROS coordinate system when camera_link didn't exist, and mistakenly ignored it. Now part of that functionality is realized in tf from base_link to camera_link.

I noticed that the map frame of the camera exists in a different position than the map frame of the ROS. The conversion is as follows:

![texclip20210617072412](https://user-images.githubusercontent.com/7959916/122307151-be28c200-cf44-11eb-9e53-092b52392dd3.png)

> So, I suppose that here should be something like this instead:
> ```
> -    map_to_camera_affine.prerotate(cv_to_ros).rotate(cv_to_ros.transpose());
> +    map_to_camera_affine.rotate(cv_to_ros);
> ```

the above proposal is corrected as follows:

```diff
-    map_to_camera_affine.prerotate(cv_to_ros).rotate(cv_to_ros.transpose());
+    map_to_camera_affine.prerotate(cv_to_ros);
```

**Comment by AlexeyMerzlyakov** [comment]
Yes, I agree with the equation above. This should be `prerotate()` instead of `rotate()`. Thank you for careful back-up!
Also checked it in Gazebo experiments: it works as expected.
One note: since _map_**T**_openvslam_map_ - is a transformation from `ROS map` coordinate system -> to `openvslam map` coordinate system, shouldn't it be named `ros_to_cv` instead of `cv_to_ros`?
