### ISSUE TITLE
Support RGB-D cameras for ROS2

### ISSUE THREAD

**Issue by AlexeyMerzlyakov** [OpenVSLAM-Community/openvslam_ros#3]
Currently, monocular and stereo modes are supported in OpenVSLAM ROS wrappers. The main goal here is to add remaining support for RGB-D cameras into OpenVSLAM-ROS wrapper.

**Comment by AlexeyMerzlyakov** [comment]
@ShivamPR21, it looks like you've interested in this.

**Comment by SteveMacenski** [comment]
You should make sure to mark this with [ROS2] since ROS1 has this already

**Comment by AlexeyMerzlyakov** [comment]
Confirm. This should be added a support only to ROS2 branch.

**Comment by ShivamPR21** [comment]
@AlexeyMerzlyakov I have created a PR for this #6

**Comment by SteveMacenski** [comment]
I think this ticket may be closed now
