### ISSUE TITLE
timestamps associated with frames are taken from clock->now() rather than image timestamp

### ISSUE THREAD

**Issue by Jconn** [OpenVSLAM-Community/openvslam_ros#40]
I'm seeing that the timestamps fed into OpenVSLAM are taken from the current system time, rather than the images received from topic subscriptions. 
[for example](https://github.com/OpenVSLAM-Community/openvslam_ros/blob/ros2/src/openvslam_ros.cc#L205)

```
    const rclcpp::Time tp_1 = node_->now();
    const double timestamp = tp_1.seconds();

    // input the current frame and estimate the camera pose
    auto cam_pose_wc = SLAM_.feed_stereo_frame(leftcv, rightcv, timestamp, mask_);
```
since these timestamps are later assigned to frames, I think its more appropriate to assign the timestamp of the image, something like
```
    const rclcpp::Time msg_time(left->header.stamp);
    const double timestamp = msg_time.seconds();
```

**Comment by jjd9** [comment]
@ymd-stella this bug was fixed here: https://github.com/stella-cv/stella_vslam_ros/pull/125
should the Issue be closed?
