### ISSUE TITLE
Make ros-distro-libg2o compatable

### ISSUE THREAD

**Issue by ryleymcc** [OpenVSLAM-Community/openvslam_ros#52]
I am trying to use openvslam for odometry in rtabmap. One issue I am having is the incompatible g2o library. issue [#200 ](https://github.com/xdspacelab/openvslam/issues/200)of the original repo.

I have a slightly different terminal output before it freezes. (--debug)
```
[2021-10-20 00:15:41.647] [D] reconstruct_with_H
[2021-10-20 00:15:41.709] [D] try to initialize with the initial frame and the current frame: frame 0 - frame 282
[2021-10-20 00:15:41.713] [D] reconstruct_with_F
[2021-10-20 00:15:41.713] [I] initialization succeeded with F
[2021-10-20 00:15:41.713] [D] DESTRUCT: initialize::perspective
```

**Comment by ryleymcc** [comment]
running `sudo dpkg --remove --force-depends ros-noetic-libg2o ` solved the issue while keeping rtabmap happy. Not sure if this will lead to issues down the line.

**Comment by ymd-stella** [comment]
Please describe the build conditions precisely. If g2o does not exist, it is impossible to build OpenVSLAM. Have you built g2o by yourself?

**Comment by ryleymcc** [comment]
Installed ROS noetic. Installed realsense2_camera. Installed rtabmap_ros with `ros-noetic-rtabmap-ros`. Created catkin_ws. Created simple package with rtabmap and realsense2_camera depends.` catkin_make`. Installed openvslam with g2o as per the installation guide. installed openvslam_ros in /catkin_ws/src/. `catkin_make`. run `./openvslam run_slam -v /dir -c /dir` and it freezes after first frame. run `sudo dpkg --remove --force-depends ros-noetic-libg2o`. `catkin_make`. openvslam runs like normal.

Rtabmap installs ros-noetic-g2o and i also installed g2o from source in openvslam install guide so there is some sort of conflict.

**Comment by ymd-stella** [comment]
I recommend not building g2o, and using only ros-noetic-libg2o.

In docker, it works fine that way.
https://github.com/OpenVSLAM-Community/openvslam_ros/blob/ros2/Dockerfile#L97

**Comment by ryleymcc** [comment]
i have it working now but yea that's something to try next time
