### ISSUE TITLE
Issue with image_transport head files.

### ISSUE THREAD

**Issue by mirellameelo** [OpenVSLAM-Community/openvslam_ros#8]
Hello! One change of the PR #6 was in the #include for **image_transport**, to something with .hpp (`<image_transport/image_transport.hpp>`). Using ROS2 **eloquent** I got errors with this (`No such file or directory`). It may be happening because of the [image common branch](https://github.com/ros-perception/image_common/tree/eloquent/image_transport/include/image_transport) used. I believe @ShivamPR21 used the [ros2 branch ](https://github.com/ros-perception/image_common/tree/ros2/image_transport/include/image_transport) which does not work for eloquent. It gives the error: `fatal error: rcpputils/get_env.hpp: No such file or directory`

In case I go back to the image_common - branch eloquent and change back the image_transport head file to `#include <image_transport/image_transport.h>`, everything goes fine.

I believe new incompatibilities can appear due to ROS2 different versions, so maybe different branches could be interesting... [?]

**Comment by SteveMacenski** [comment]
Eloquent is EOL on all platforms, so I don't think we should be doing anything specifically targeting that if its not an issue in dashing or foxy. I haven't tested on anything though to know if its an issue for the other distros.

**Comment by mirellameelo** [comment]
When using dashing environment, the packages were successfully built for [dashing branch](https://github.com/ros-perception/image_common/tree/dashing) 
When using [ROS2 branch](https://github.com/ros-perception/image_common/tree/ros2) I got much more errors than in the eloquent environment

**Comment by SteveMacenski** [comment]
this looks like something to be filed in the image_common repo?

**Comment by mirellameelo** [comment]
Even if they have a "dashing" branch that is working fine? Also, fixing this can lead to errors in foxy... edit: I'm assuming ros2 branch is aimed to foxy. Edit_2: seems that worked once the [ros2 branch for dashing](https://github.com/ros-perception/image_common/issues/166#issue-667592548). I'll open an issue in there.

**Comment by SteveMacenski** [comment]
ros2 is master builds

**Comment by ShivamPR21** [comment]
@mirellameelo I have changed the headers in the view of the [depreacation warning](https://github.com/ros-perception/image_common/blob/4c5053ecf703a58c25a712d1d4a80012f5076a1f/image_transport/include/image_transport/image_transport.h#L41).

**Comment by ymd-stella** [comment]
I think the problem has been solved, so I'll close it.
